In [1]:
import pandas as pd
import numpy as np
import folium
import matplotlib.pyplot as plt


hist_df = pd.read_excel('historical runs.xlsx')

hist_df = hist_df.dropna(subset='Round').reset_index(drop = True)
hist_df = hist_df[hist_df['Planned Distance'] != 'NaNkm'].reset_index(drop = True)

hist_df[['completed Drops', 'Total Drops']] = hist_df['Completed'].str.split('/', expand=True)

# Converting to numeric type if needed
hist_df[['completed Drops', 'Total Drops']] = hist_df[['completed Drops', 'Total Drops']].apply(pd.to_numeric)

hist_df = hist_df[hist_df['completed Drops'] != 0].reset_index()
hist_df = hist_df[~hist_df['completed Drops'].isna()].reset_index()


hist_df['distance'] = hist_df['Planned Distance'].str.replace('km', '', regex=True).astype(int)

hist_df['KM Cost'] = (hist_df['distance'] - 200) * 1
# Ensuring 'KM Cost' is not negative
hist_df['KM Cost'] = np.where(hist_df['KM Cost'] < 0, 0, hist_df['KM Cost'])

hist_df['Drop Cost'] = (hist_df['completed Drops'] - 70) * 4.5
# Ensuring 'KM Cost' is not negative
hist_df['Drop Cost'] = np.where(hist_df['Drop Cost'] < 0, 0, hist_df['Drop Cost'])

# Ensure the column is in datetime format
hist_df['Pln Start Date'] = pd.to_datetime(hist_df['Pln Start Date'], errors='coerce')

# Create a new column for the day of the week
hist_df['Day of Week'] = hist_df['Pln Start Date'].dt.day_name()

hist_df['Flat rate Cost'] = 370
hist_df['Total Cost'] = hist_df['KM Cost'] + hist_df['Drop Cost']+ hist_df['Flat rate Cost']
hist_df['Cost per Drop'] = hist_df['Total Cost']/hist_df['completed Drops']



# print('No. of runs:' , len(hist_df.groupby(['Round', 'Pln Finish Date']).count()))
# print('No. of drops:' , int(hist_df['completed Drops'].sum()))
# print('Max Km Bonus cost:' , hist_df['KM Cost'].max())
# print('Min Km Bonus cost:' , hist_df['KM Cost'].min())
# print('Avg Km Bonus cost:' , round(hist_df['KM Cost'].mean(), 2))
# print('Max Drop Bonus cost:' , hist_df['Drop Cost'].max())
# print('Min Drop Bonus cost:' , hist_df['Drop Cost'].min())
# print('Avg Drop Bonus cost:' , round(hist_df['Drop Cost'].mean(), 2))

In [2]:
# for dow in ['Monday']:
for dow in ['Tuesday']:

# for dow in hist_df['Day of Week'].unique():
    dow_hist_df = hist_df[hist_df['Day of Week'] == dow]

    dict_dow = {
        
    'No. of Runs' : len(dow_hist_df.groupby(['Round', 'Pln Finish Date']).count()),
    'Total No. of Drops' : int(dow_hist_df['completed Drops'].sum()),
    'Min No. of Drops' : dow_hist_df['completed Drops'].min(),
    'Max No. of Drops' : dow_hist_df['completed Drops'].max(),
    'Max Km Bonus Cost' : dow_hist_df['KM Cost'].max(),
    # 'Min Km Bonus cost' : dow_hist_df['KM Cost'].min(),
    'Avg Km Bonus Cost' : round(dow_hist_df['KM Cost'].mean(), 2),
    'Max Drop Bonus Cost' : dow_hist_df['Drop Cost'].max(),
    # 'Min Drop Bonus Cost' : dow_hist_df['Drop Cost'].min(),
    'Avg Drop Bonus Cost' : round(dow_hist_df['Drop Cost'].mean(), 2),
    'Total Cost': round(dow_hist_df['Total Cost'].sum(), 2),
    'Max Cost per Drop' : round(dow_hist_df['Cost per Drop'].max(), 2),
    'Avg Cost per Drop' : round(dow_hist_df['Cost per Drop'].mean(), 2),
    'Min Cost per Drop' : round(dow_hist_df['Cost per Drop'].min(), 2)
    }

    stats_table_df = pd.DataFrame(dict_dow, index=[0]).T.reset_index()
    stats_table_df.columns = ['Metric', 'Value']

In [3]:
dow_hist_df

,level_0,index,Round,Slot,Pln Start,Est Finish,Pln Start Date,Pln Finish Date,Zone,Suburb,...,Sequence,completed Drops,Total Drops,distance,KM Cost,Drop Cost,Day of Week,Flat rate Cost,Total Cost,Cost per Drop
64,64,64,3701.0,PM,07:30:00,NaN,2025-02-11,2025-02-11,VIC Mornington Peninsula,ROSEBUD,...,NaN,76.0,76.0,172,0,27.0,Tuesday,370,397.0,5.223684
65,65,65,3702.0,PM,07:30:00,NaN,2025-02-11,2025-02-11,VIC Mornington Peninsula,SOMERVILLE,...,NaN,69.0,69.0,222,22,0.0,Tuesday,370,392.0,5.681159
66,66,66,3703.0,PM,07:30:00,NaN,2025-02-11,2025-02-11,VIC Mornington Peninsula,MOUNT MARTHA,...,NaN,87.0,87.0,149,0,76.5,Tuesday,370,446.5,5.132184
67,67,67,3704.0,PM,07:30:00,NaN,2025-02-11,2025-02-11,VIC Melbourne Metro,FRANKSTON,...,NaN,93.0,93.0,157,0,103.5,Tuesday,370,473.5,5.091398
68,68,68,3705.0,PM,07:30:00,NaN,2025-02-11,2025-02-11,VIC Melbourne Metro,CARRUM DOWNS,...,NaN,85.0,85.0,169,0,67.5,Tuesday,370,437.5,5.147059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,496,496,3734.0,PM,08:00:00,NaN,2025-02-04,2025-02-04,VIC Outer Melbourne West,SUNBURY,...,NaN,82.0,82.0,214,14,54.0,Tuesday,370,438.0,5.341463
494,497,497,3735.0,PM,08:00:00,NaN,2025-02-04,2025-02-04,VIC Melbourne Metro,HURSTBRIDGE,...,NaN,82.0,82.0,198,0,54.0,Tuesday,370,424.0,5.170732
508,511,511,37061.0,PM,18:17:00,NaN,2025-02-04,2025-02-04,VIC Melbourne Metro,FRANKSTON,...,NaN,41.0,41.0,91,0,0.0,Tuesday,370,370.0,9.024390
509,512,512,37101.0,PM,17:22:00,NaN,2025-02-04,2025-02-04,VIC Melbourne Metro,ST KILDA EAST,...,NaN,41.0,41.0,39,0,0.0,Tuesday,370,370.0,9.024390
510,513,513,37261.0,PM,19:48:00,NaN,2025-02-04,2025-02-04,VIC Melbourne Metro,FITZROY NORTH,...,NaN,39.0,39.0,45,0,0.0,Tuesday,370,370.0,9.487179

In [4]:
round_list_am = []
round_list_pm = []


for date in dow_hist_df['Pln Start Date'].unique():
    for slot in dow_hist_df['Slot'].unique():
        if slot == 'AM':
            round_list_am.append(len(dow_hist_df[(dow_hist_df['Pln Start Date'] == date) & (dow_hist_df['Slot'] == slot)]['Round'].unique()))
        if slot == 'PM':
            round_list_pm.append(len(dow_hist_df[(dow_hist_df['Pln Start Date'] == date) & (dow_hist_df['Slot'] == slot)]['Round'].unique()))

In [5]:
dow_hist_df.nunique()

level_0             74
index               74
Round               39
Slot                 1
Pln Start            7
Est Finish           0
Pln Start Date       2
Pln Finish Date      2
Zone                 5
Suburb              54
Completed           30
Drops                0
Last Drop            1
Driver              42
Contractor          18
Planned Distance    59
Actual Start        57
Actual Finish       69
More Info            0
Sequence             0
completed Drops     26
Total Drops         24
distance            59
KM Cost             14
Drop Cost           22
Day of Week          1
Flat rate Cost       1
Total Cost          30
Cost per Drop       36
dtype: int64

In [7]:
round_list = dow_hist_df.groupby(['Pln Start Date'])['Round'].nunique().tolist()
round_list

[38, 36]

In [8]:
stats_table_df

                 Metric     Value
0           No. of Runs     74.00
1    Total No. of Drops   5718.00
2      Min No. of Drops     39.00
3      Max No. of Drops     94.00
4     Max Km Bonus Cost     43.00
5     Avg Km Bonus Cost      3.45
6   Max Drop Bonus Cost    108.00
7   Avg Drop Bonus Cost     47.01
8            Total Cost  31113.50
9     Max Cost per Drop      9.49
10    Avg Cost per Drop      5.64
11    Min Cost per Drop      5.09

In [9]:
# Compute minimum cost per drop, associated number of drops, and total driving distance per round
rounds = list(dow_hist_df['Round'].unique())
min_cost_per_drop = []
associated_drops = []
total_driving_distance = []

for rnd in rounds:
    round_df = hist_df[hist_df['Round'] == rnd]
    min_cost_per_drop.append(round_df['Cost per Drop'].min())
    associated_drops.append(round_df.loc[round_df['Cost per Drop'].idxmin(), 'completed Drops'])
    total_driving_distance.append(round_df.loc[round_df['Cost per Drop'].idxmin(), 'distance'])

In [25]:
# route_stats = pd.read_csv('Adiona_output/5373978218594304_stats.csv') # Upload 1
# drops_stats = pd.read_csv('Adiona_output/5373978218594304.csv') # Upload 2

route_stats = pd.read_csv('Adiona_output/5171617546108928_stats.csv') # Upload 1
drops_stats = pd.read_csv('Adiona_output/5171617546108928.csv') # Upload 2

# route_stats = pd.read_csv('Adiona_output/6119165295329280_stats.csv') # Upload 1
# drops_stats = pd.read_csv('Adiona_output/6119165295329280.csv') # Upload 2

# route_stats = pd.read_csv('Adiona_output/5650051116302336_stats.csv') # Upload 1
# drops_stats = pd.read_csv('Adiona_output/5650051116302336.csv') # Upload 2


# routes_metro = route_stats[route_stats['rateZone'] == 'Melbourne Metro'].reset_index(drop = True)
list_zone = []

for zone_val in route_stats['zone'].unique():
    if 'Metro' in zone_val or 'metro' in zone_val:
        list_zone.append(zone_val)
routes_metro = route_stats[route_stats['zone'].isin(list_zone)].reset_index(drop = True)


drops_metro = drops_stats[drops_stats['RouteId'].isin(routes_metro['routeClient'].values.tolist())].reset_index(drop = True)


routes_metro['KM Cost'] = (routes_metro['drivingDistance']/1000 - 200) * 1
routes_metro['KM Cost'] = np.where(routes_metro['KM Cost'] < 0, 0, routes_metro['KM Cost'])

routes_metro['No. of overloaded drops'] = routes_metro['d2'] -70
# routes_metro['No. of overloaded drops'] = np.where(routes_metro['No. of overloaded drops'] < 0, 0, routes_metro['No. of overloaded drops'])

routes_metro['Drop Cost'] = (routes_metro['d2'] - 70) * 4.5
routes_metro['Drop Cost'] = np.where(routes_metro['Drop Cost'] < 0, 0, routes_metro['Drop Cost'])

routes_metro['Flat Rate'] = [350 for i in range(len(routes_metro))]

routes_metro['Total Cost'] = routes_metro['KM Cost'] + routes_metro['Drop Cost'] + routes_metro['Flat Rate']

routes_metro['Cost per Drop'] = routes_metro['Total Cost']/routes_metro['d1']
if len(routes_metro[routes_metro['No. of overloaded drops'] <= 0]) > 0:
    print('Route have capacity: ', routes_metro[routes_metro['No. of overloaded drops'] <= 0][['routeClient', 'No. of overloaded drops']])

# if routes_metro[routes_metro['No. of overloaded drops'] > 0]['No. of overloaded drops'].sum() > 77:

Route have capacity:     routeClient  No. of overloaded drops
0         3001                      -42
1         3002                      -40
2         3003                      -43
3         3004                      -45
4         3005                      -40
5         3006                      -49

In [26]:
routes_metro[routes_metro['Cost per Drop'] > 370/70]

,zone,shift,routeClient,vehicle,cost,rateZone,drivingDistance,drivingTime,totalTime,co2,d1,d2,KM Cost,No. of overloaded drops,Drop Cost,Flat Rate,Total Cost,Cost per Drop
0,VIC Melbourne Metro & VIC Outer Melbourne West...,day,3001,VAN5,$487.82,Truck,115060,11931,24900,80kg,28,28,0.0,-42,0.0,350,350.0,12.500000
1,VIC Melbourne Metro & VIC Outer Melbourne West...,day,3002,VAN1,$420.61,Truck,51238,8463,22521,36kg,30,30,0.0,-40,0.0,350,350.0,11.666667
2,VIC Melbourne Metro & VIC Outer Melbourne West...,day,3003,VAN4,$512.78,Truck,108725,13648,26442,76kg,27,27,0.0,-43,0.0,350,350.0,12.962963
3,VIC Melbourne Metro & VIC Outer Melbourne West...,day,3004,VAN6,$463.80,Truck,108582,11711,23692,76kg,25,25,0.0,-45,0.0,350,350.0,14.000000
4,VIC Melbourne Metro & VIC Outer Melbourne West...,day,3005,VAN3,$470.62,Truck,82741,10142,24642,58kg,30,30,0.0,-40,0.0,350,350.0,11.666667
5,VIC Melbourne Metro & VIC Outer Melbourne West...,day,3006,VAN2,$427.36,Truck,90502,8202,22040,63kg,21,21,0.0,-49,0.0,350,350.0,16.666667

In [12]:
drops_stats

,Id,Address,Name,d1,Latitude,Longitude,ClientDeliveryWindowStart,ClientDeliveryWindowFinish,Depot,RouteId,LegId,VehicleId,Shift,ZoneId,SequenceId,ArrivalTime,DepartureTime
0,35449558,"12-18 DISTRIBUTION DRIVE, , TRUGANINA, VIC, 3029",Lactalis (Tullamarine VIC),1,-37.815871,144.759863,03:00,07:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,1,05:53,06:01
1,35449567,"26 AILSA STREET SOUTH, , LAVERTON, VIC, 3028",Lactalis (Tullamarine VIC),1,-37.869275,144.762120,01:00,07:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,2,06:17,06:26
2,35449578,"8-10 RUSSELL STREET, , WERRIBEE, VIC, 3030",Lactalis (Tullamarine VIC),1,-37.908280,144.664468,03:00,09:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,3,06:40,06:45
3,35449577,"137-139 PRINCES HIGHWAY, , WERRIBEE, VIC, 3030",Lactalis (Tullamarine VIC),1,-37.893317,144.680956,01:00,07:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,4,06:52,06:57
4,35449576,"240 HOPPERS LANE, , WERRIBEE, VIC, 3030",Lactalis (Tullamarine VIC),1,-37.887348,144.702660,06:00,10:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,5,07:01,07:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,35449690,"21 HIGH ST, , LANCEFIELD, VIC, 3435",Lactalis (Tullamarine VIC),1,-37.277367,144.733813,08:00,12:00,Tullamarine,3007,leg1,VAN1,day,VIC Bendigo,8,08:39,08:49
169,35449689,"74 MAIN ROAD, , LANCEFIELD, VIC, 3435",Lactalis (Tullamarine VIC),1,-37.277229,144.737149,05:00,09:00,Tullamarine,3007,leg1,VAN1,day,VIC Bendigo,9,08:51,08:57
170,35449691,"128 HIGH STREET, , WOODEND, VIC, 3442",Lactalis (Tullamarine VIC),1,-37.356225,144.528726,07:00,12:00,Tullamarine,3007,leg1,VAN1,day,VIC Bendigo,10,09:20,09:27
171,35449692,"55 HIGH ST, , KYNETON, VIC, 3444",Lactalis (Tullamarine VIC),1,-37.250110,144.455718,05:30,11:00,Tullamarine,3007,leg1,VAN1,day,VIC Bendigo,11,09:41,09:53
172,35449693,"62 MOLLISON STREET, , KYNETON, VIC, 3444",Lactalis (Tullamarine VIC),1,-37.250114,144.453259,07:00,12:00,Tullamarine,3007,leg1,VAN1,day,VIC Bendigo,12,09:54,10:08

In [13]:
# Define categories based on conditions
need_to_be_refined = routes_metro[(routes_metro['d2'] < 70) & (routes_metro['Cost per Drop'] > 370/70) | (routes_metro['Cost per Drop'] > 6)]['routeClient'].values.tolist()
good = routes_metro[(routes_metro['d2'] >= 70) & (routes_metro['Cost per Drop'] < 370/70) & (routes_metro['drivingDistance']/1000 < 200)].values.tolist()
# can_be_refined = routes_metro[(routes_metro['d2'] < 70) | (routes_metro['drivingDistance']/1000 > 200)]['routeClient'].values.tolist()

# Define 'Can be refined' as those that are neither in 'Need to be refined' nor in 'Good'
all_routes = set(routes_metro['routeClient'])
can_be_refined = list(all_routes - set(need_to_be_refined) - set(good))

In [14]:
routes_metro[(routes_metro['d2'] >= 70) & (routes_metro['Cost per Drop'] < 370/70) & (routes_metro['drivingDistance']/1000 < 200)]

Empty DataFrame
Columns: [zone, shift, routeClient, vehicle, cost, rateZone, drivingDistance, drivingTime, totalTime, co2, d1, d2, KM Cost, No. of overloaded drops, Drop Cost, Flat Rate, Total Cost, Cost per Drop]
Index: []

In [15]:
# 'Need to be refined': routes_metro[(routes_metro['No. of overloaded drops'] < 0) | (routes_metro['drivingDistance']/1000 > 200)]['routeClient'].values.tolist()
# 'Good': routes_metro[(routes_metro['d2'] > 70) & (routes_metro['drivingDistance']/1000 < 200)]['routeClient'].values.tolist()

In [16]:
# Generate unique colors using 'gist_ncar' for more diversity
route_ids = sorted(drops_metro['RouteId'].unique())  # Sorting to maintain order
num_routes = len(route_ids)
colors = plt.cm.gist_ncar(np.linspace(0, 1, num_routes))  # More distinguishable colors

# Convert colors to hex values
route_colors = {route: f'#{int(c[0]*255):02x}{int(c[1]*255):02x}{int(c[2]*255):02x}' for route, c in zip(route_ids, colors)}

# Initialize the map
m = folium.Map(location=[drops_metro['Latitude'].mean(), drops_metro['Longitude'].mean()], zoom_start=12)

# Add points with unique colors
for _, row in drops_metro.iterrows():
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=5,
        color=route_colors[row['RouteId']],
        fill=True,
        fill_color=route_colors[row['RouteId']],
        fill_opacity=0.7,
        popup=f"Route ID: {row['RouteId']}"
    ).add_to(m)

# Add a legend manually with a scrollbar for large lists
legend_html = '''
<div style="position: fixed; 
            bottom: 50px; left: 50px; width: auto; height: auto; 
            overflow-y: auto; background-color: white; z-index:9999; 
            padding: 10px; font-size:14px; border-radius:5px; 
            box-shadow: 0px 0px 5px gray;">
    <b>Route ID</b><br>
'''
for route, color in route_colors.items():
    legend_html += f'<div style="display: flex; align-items: center;"><div style="width: 12px; height: 12px; background: {color}; margin-right: 5px;"></div>{route}</div>'

legend_html += '</div>'

m.get_root().html.add_child(folium.Element(legend_html))

# Display map
m

In [17]:
drops_metro.isna().sum()

Id                            0
Address                       0
Name                          0
d1                            0
Latitude                      0
Longitude                     0
ClientDeliveryWindowStart     0
ClientDeliveryWindowFinish    0
Depot                         0
RouteId                       0
LegId                         0
VehicleId                     0
Shift                         0
ZoneId                        0
SequenceId                    0
ArrivalTime                   0
DepartureTime                 0
dtype: int64

In [18]:
drops_metro

,Id,Address,Name,d1,Latitude,Longitude,ClientDeliveryWindowStart,ClientDeliveryWindowFinish,Depot,RouteId,LegId,VehicleId,Shift,ZoneId,SequenceId,ArrivalTime,DepartureTime
0,35449558,"12-18 DISTRIBUTION DRIVE, , TRUGANINA, VIC, 3029",Lactalis (Tullamarine VIC),1,-37.815871,144.759863,03:00,07:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,1,05:53,06:01
1,35449567,"26 AILSA STREET SOUTH, , LAVERTON, VIC, 3028",Lactalis (Tullamarine VIC),1,-37.869275,144.762120,01:00,07:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,2,06:17,06:26
2,35449578,"8-10 RUSSELL STREET, , WERRIBEE, VIC, 3030",Lactalis (Tullamarine VIC),1,-37.908280,144.664468,03:00,09:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,3,06:40,06:45
3,35449577,"137-139 PRINCES HIGHWAY, , WERRIBEE, VIC, 3030",Lactalis (Tullamarine VIC),1,-37.893317,144.680956,01:00,07:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,4,06:52,06:57
4,35449576,"240 HOPPERS LANE, , WERRIBEE, VIC, 3030",Lactalis (Tullamarine VIC),1,-37.887348,144.702660,06:00,10:00,Tullamarine,3001,leg1,VAN5,day,VIC Melbourne Metro & VIC Outer Melbourne West...,5,07:01,07:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,35449706,"4A McCormacks Rd, , MADDINGLEY, VIC, 3340",Lactalis (Tullamarine VIC),1,-37.688453,144.412848,06:30,10:30,Tullamarine,3006,leg1,VAN2,day,VIC Melbourne Metro & VIC Outer Melbourne West...,17,09:55,10:07
157,35449705,"1-9 BENNETT STREET, , BACCHUS MARSH, VIC, 3340",Lactalis (Tullamarine VIC),1,-37.674234,144.437668,06:30,10:30,Tullamarine,3006,leg1,VAN2,day,VIC Melbourne Metro & VIC Outer Melbourne West...,18,10:13,10:20
158,35449679,"151 Gisborne Rd, , BACCHUS MARSH, VIC, 3340",Lactalis (Tullamarine VIC),1,-37.659268,144.441409,06:30,10:30,Tullamarine,3006,leg1,VAN2,day,VIC Melbourne Metro & VIC Outer Melbourne West...,19,10:24,10:33
159,35449695,553-555 HIGH STREET\nWoodgrove Shopping Centre...,Lactalis (Tullamarine VIC),1,-37.686378,144.566501,08:30,13:00,Tullamarine,3006,leg1,VAN2,day,VIC Melbourne Metro & VIC Outer Melbourne West...,20,10:46,10:55
160,35449708,"533-555 HIGH ST, WOODGROVE S/C, , MELTON, VIC,...",Lactalis (Tullamarine VIC),1,-37.686230,144.561474,08:00,13:00,Tullamarine,3006,leg1,VAN2,day,VIC Melbourne Metro & VIC Outer Melbourne West...,21,11:00,11:07

In [19]:
route_colors

{3001: '#000080',
 3002: '#00edff',
 3003: '#73e800',
 3004: '#ffcd05',
 3005: '#f106ff',
 3006: '#fef7fe'}

In [20]:
for dow in ['Monday']:
# for dow in hist_df['Day of Week'].unique():
    dow_hist_df = hist_df[hist_df['Day of Week'] == dow]   


    rounds = list(dow_hist_df['Round'].unique())
    min_cost_per_drop = []
    associated_drops = []
    total_driving_distance = []

    for rnd in rounds:
        round_df = dow_hist_df[dow_hist_df['Round'] == rnd]
        min_cost_per_drop.append(round_df['Cost per Drop'].min())
        associated_drops.append(round_df.loc[round_df['Cost per Drop'].idxmin(), 'completed Drops'])
        total_driving_distance.append(round_df.loc[round_df['Cost per Drop'].idxmin(), 'distance'])

    rounds = [str(int(i)) for i in rounds]
    # Create DataFrame for visualization

    round_stats_df = pd.DataFrame({
        'Round': rounds,
        'Min Cost per Drop': min_cost_per_drop,
        'Associated Drops': associated_drops,
        'Total Driving Distance': total_driving_distance
    })

In [21]:
# Assuming round_stats_df is already loaded in the environment, let's sort it based on the 'Total Driving Distance' column

# Sorting the dataframe by 'Total Driving Distance' in ascending order
round_stats_df = round_stats_df.sort_values(by='Total Driving Distance', ascending=True)

In [23]:
round_stats_df

    Round  Min Cost per Drop  Associated Drops  Total Driving Distance
67  37091           9.024390              41.0                      33
63  37041           9.250000              40.0                      37
71  39111          24.666667              15.0                      41
10   3710           5.139535              86.0                      52
70  39031           6.271186              59.0                      58
..    ...                ...               ...                     ...
35   3735           5.162651              83.0                     200
25   3725           5.376543              81.0                     216
66   3751          10.102564              39.0                     224
64   3202           5.955224              67.0                     229
65   3750          14.033333              30.0                     251

[72 rows x 4 columns]

In [24]:
print(round(100*2/23, 3))
print(round(100*21/23, 3))

8.696
91.304